version: 2.1

jobs:
  compile-test-package:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: fx-price-handler-cache-{{ checksum "pom.xml" }}
      - run:
          name: Download dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: fx-price-handler-cache-{{ checksum "pom.xml" }}
      - run:
          name: Run tests
          command: mvn verify
      - run:
          name: Build jar
          command: mvn package
      - run:
          name: Unpack fat jar
          command: mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
      - run:
          name: Build docker image
          command: docker compose -f docker/app.yml build
      - persist_to_workspace:
          root: .
          paths:
            - target/dependency/*
            - Dockerfile

workflows:
  compile-test-package:
    jobs:
      - compile-test-package
