version: 2.1

jobs:
  compile-test-package:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: fx-price-handler-cache-{{ checksum "pom.xml" }}
      - run:
          name: Download dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: fx-price-handler-cache-{{ checksum "pom.xml" }}
      - run:
          name: Run tests
          command: mvn verify
      - run:
          name: Build jar
          command: mvn package
      - run:
          name: Unpack fat jar
          command: mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
      - persist_to_workspace:
          root: .
          paths:
            - target/dependency/*
            - Dockerfile

  build-docker:
    docker:
      - image: cimg/base:2022.06
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - attach_workspace:
          at: .
      - run: docker build -t patrykkrawczyk/fx-price-handler-app:$CIRCLE_BRANCH .

workflows:
  compile-test-package:
    jobs:
      - compile-test-package
      - build-docker:
          requires:
            - compile-test-package
